### ISSUE TITLE
Does not work in Docker when user is not root

### ISSUE THREAD

**Issue by jrb-cobot** [rbonghi/jetson_stats#391]
## Describe the bug

I have made a non-root user in my container. Jtop does not run. When running the container as root, it works fine. 

In my Dockerfile, before making the user, I have this line which runs as root: 
`RUN python3 -m pip install -U jetson-stats`. This is the behavior I want--install as root, run as non-root. 

## To Reproduce

`docker run ...`
```bash
I can't access jtop.service.
Please logout or reboot this board
```

`docker run --user root ...`
Jtop works as normal. 

## Expected behavior

After installation, jtop should run without `sudo`, just as in the non-containerized case. 

### Board

Output from `jetson_release -v`:
```
Software part of jetson-stats 4.2.1 - (c) 2023, Raffaello Bonghi
Model: Jetson AGX Orin - Jetpack 5.0.2 GA [L4T 35.1.0]
NV Power Mode[0]: MAXN
Serial Number: [XXX Show with: jetson_release -s XXX]
Hardware:
 - 699-level Part Number: 699-13701-0000-500 L.0
 - P-Number: p3701-0000
 - Module: NVIDIA Jetson AGX Orin
 - SoC: tegra23x
 - CUDA Arch BIN: 8.7
 - Codename: Concord
Platform:
 - Machine: aarch64
 - System: Linux
 - Distribution: Ubuntu 20.04 focal
 - Release: 5.10.104-tegra
 - Python: 3.8.10
jtop:
 - Version: 4.2.1
 - Service: Active
Libraries:
 - CUDA: 11.4.239
 - cuDNN: 8.4.1.50
 - TensorRT: 5.0.2
 - VPI: 2.1.6
 - Vulkan: 1.3.203
 - OpenCV: 4.5.4 - with CUDA: NO
```
