### ISSUE TITLE
No GPU temperature when running jtop inside a docker container

### ISSUE THREAD

**Issue by livneros-greeneye** [rbonghi/jetson_stats#432]
## Describe the bug

While running jtop inside a docker container, the GPU temperature details are offline.

## To Reproduce

```
from jtop import jtop
jetson = jtop()
jetson.start()
jetson.temperature["GPU"]

```

1. Running the following commands on my host plots:
`> {'temp': -256.0, 'online': False}`
2. Running a docker container, as mentioned in the [documentation](https://rnext.it/jetson_stats/docker.html):
`docker run --rm -it -v /run/jtop.sock:/run/jtop.sock rbonghi/jetson_stats:latest` plots:
`> {'temp': 39.875, 'online': True}`

The same issue happens while using `jtop`:
1. On host:
![image](https://github.com/rbonghi/jetson_stats/assets/116816952/4aa77fb5-dfda-42a6-a824-b12c0d075cd5)
2. Inside the docker container:
![image](https://github.com/rbonghi/jetson_stats/assets/116816952/162158da-0cf5-4a7c-bbdc-b5a65014588e)

### Board

```
Software part of jetson-stats 4.2.2 - (c) 2023, Raffaello Bonghi
Model: Jetson AGX Orin as NX-16GB - Jetpack 5.1.1 [L4T 35.3.1]
NV Power Mode[0]: MAXN
Serial Number: [XXX Show with: jetson_release -s XXX]
Hardware:
 - 699-level Part Number: 699-13701-0005-500 M.0
 - P-Number: p3701-0005
 - Module: NVIDIA Jetson AGX Orin (64GB ram)
 - SoC: tegra23x
 - CUDA Arch BIN: 8.7
 - Codename: Concord
Platform:
 - Machine: aarch64
 - System: Linux
 - Distribution: Ubuntu 20.04 focal
 - Release: 5.10.104-tegra
 - Python: 3.8.10
jtop:
 - Version: 4.2.2
 - Service: Active
Libraries:
 - CUDA: 11.4.315
 - cuDNN: 8.6.0.166
 - TensorRT: 5.1.1
 - VPI: 2.2.7
 - Vulkan: 1.3.204
 - OpenCV: 4.5.4 - with CUDA: NO
```
